- hosts: tomcat
  vars:
    newrelic_license_key: XXXXXXXXXXX
    java_packages:
      - oracle-java8-installer
    mysql_root_password: root
    mysql_databases:
      - name: thedatabase
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: theuser
        host: "%"
        password: theuser
        priv: "thedatabase.*:ALL"

  sudo: yes
  roles:
    - common
#   - newrelic
    - java
#    - mysql
