- name: install python3.4
  apt: name=python3.4 update_cache=yes
  tags: python3

- name: be sure pip is installed
  apt: name=python-pip update_cache=yes
  tags: python3

- name: be sure pip is installed for python3
  apt: name=python3-pip update_cache=yes
  tags: python3

- name: install virtualenv for python
  pip: name=virtualenv
